version: '2'
services:
    21points-mysql:
        container_name: 21points-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/21points/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=21points
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
